### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/itsb#1]
The website is a rebuild of https://sameboats.org/. It should be built following core principles of [minicomp](https://minicomp.github.io/wiki/), consistent with using mature, widely deployed tech. It should have sections for:

- [x] [Navigation and layout](https://github.com/performant-software/itsb/issues/11)
- [x] [Trajectories/Intersections (integrate with react-router)](https://github.com/performant-software/itsb/issues/7)
- [x] [Home, Credits, Instructions](https://github.com/performant-software/itsb/issues/8)
- [x] [Search](https://github.com/performant-software/itsb/issues/10)
- [x] [Design for mobile](https://github.com/performant-software/itsb/issues/48)

Candidates for a framework could include, but are not limited to:
- [Jekyll](https://jekyllrb.com/)
- [Next.js](https://nextjs.org/)
- [Create React App](https://create-react-app.dev/)
- [Remix.run](Remix.run) (which tells compelling accessibility and progressive enhancement stories)
- Hugo (go)
- Gatsby (js)
- Etc.
